import React from "react";
import Head from "next/head";
// COMPONENTS
import Navigation from "./components/Navigation";
import Header from "./components/Header";
import Featured from "./components/Featured";
import Banner from "./components/Banner";
import Services from "./components/Services";
import About from "./components/About";
import Contact from "./components/Contact";
import Footer from "./components/Footer";
import Map from "./components/Map";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <Header />
      <Banner />
      <Featured />
      <Services />
      <About />
      <Map />
      <Contact />
      <Footer />
    </div>
  );
}
